// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * Enable cache control header
       */
      enableCacheControlHeader: boolean;

      /**
       * Max Age in Seconds (max-age)
       */
      maxAge?: string;

      /**
       * Shared Max Age in Seconds (s-maxage)
       */
      sMaxAge?: string;

      /**
       * Include LastModified header
       */
      includeLastModified: boolean;
    }
  }
}
